### ISSUE TITLE
‼️Calculate ner performance of StringTagger

### ISSUE THREAD

**Issue by juanmirocks** [juanmirocks/LocText#37]
* [x] Here is about getting the ner P, R, and F for the StringTagger to recognize:

* Proteins
* Localization
* Organism

should be trivial to do; all is implemented and nala shows all the code to do it. We compare with **"partial"** matching

* [x] Get P, R, and F for the 3 entity classes, yet now evaluating the **normalization ids**. A true positive is if the two entities partially match and their normalization ids are equal.

## Tests

* [ ] Run nala and get its exact and overlapping performance — nala with `EvaluationMentor` must report the same performance measures as before --- nala must not be modified -- a script or similar or not modifed code on `train.py` (nala) without committing suffices

The requirements:

1. `EntityEvaluator` must have ONLY two functions regarding this: `entity_map_fun` and `entity_accept_fun` (the overlapping_fun is NOT needed)

2. nalaf code should not have any mention about the constants `PRO_ID, ....`
 
3. You do not split by `::` or anything in `EntityEvaluator` — You do the splitting in a passed function, for example in `evaluations.py`
  
4. You likely do not need the function `map_entities` as it’s very trivial
  
5. You definitely do not traverse two lists of entities in the optional `map_entities`
  
6. Once again, `entity_map_fun` is a function that takes an entity and converts it to a string. For example, you can convert the entity to its offsets `start,end` (edited)
 
7. Once again, `entity_accept_fun` takes two strings as parameters (gold and pred) and decides whether to accept the prediction (return True), ignore it (return None), or reject it (return False)
 
8. I, the user of LocText, can call `EntityEvaluator` to either get the performance of `overlapping` entities (meaning, overlapping == exact or overlapping, and don’t care about normalizations), or I care both about overlapping AND the normalization — or actually, anything else I want — I could also want to check the performance of exact only ---- I already told you in the university how to do all of this
  
9. Essentially, EntityEvaluator code will be THE SAME as `DocumentLevalEvaluator` — As a matter of fact, one could think how even to integrate both into one only — but not needed now — Bottom line, you don’t have to break you head about the inner body of EntityEvaluator, you basically only need to copy

10. Finally, when you MentionLevelEvaluator and get the overlapping performance for LocText and nala, this should be EXACTLY THE SAME, as when you get the overlapping performance with `EntityEvaluator`

**Comment by MadhukarSP** [comment]
MentionLevelEvaluator performance [Entity.equality_operator = 'exact_or_overlapping']
-----------------------------------------------------------------------------------
# class	tp	fp	fn	fp_ov	fn_ov	e|P	e|R	e|F	e|F_SE	o|P	o|R	o|F	o|F_SE
TOTAL	1809	197	422	0	0	0.9018	0.8108	0.8539	0.0010	0.9018	0.8108	0.8539	0.0011
e_1	1142	161	253	0	0	0.8764	0.8186	0.8466	0.0013	0.8764	0.8186	0.8466	0.0013
e_2	404	33	155	0	0	0.9245	0.7227	0.8112	0.0024	0.9245	0.7227	0.8112	0.0023
e_3	263	3	14	0	0	0.9887	0.9495	0.9687	0.0009	0.9887	0.9495	0.9687	0.0009
-----------------------------------------------------------------------------------

EntityEvaluator performance
-----------------------------------------------------------------------------------
# class	tp	fp	fn	fp_ov	fn_ov	e|P	e|R	e|F	e|F_SE	o|P	o|R	o|F	o|F_SE
TOTAL	1509	282	488	0	0	0.8425	0.7556	0.7967	0.0014	0.8425	0.7556	0.7967	0.0014
e_1	871	229	291	0	0	0.7918	0.7496	0.7701	0.0019	0.7918	0.7496	0.7701	0.0019
e_2	382	43	176	0	0	0.8988	0.6846	0.7772	0.0026	0.8988	0.6846	0.7772	0.0026
e_3	256	10	21	0	0	0.9624	0.9242	0.9429	0.0013	0.9624	0.9242	0.9429	0.0013
-----------------------------------------------------------------------------------

Performance in MentionLevelEvaluator is better than EntityEvaluator, because we do not check the equality of entities [predicted and gold] based on normalization ID's in MentionLevelEvaluator

**Comment by MadhukarSP** [comment]
### 1) MentionLevelEvaluator *[overlapping and exact] - Existing one*

class	tp	fp	fn	fp_ov	fn_ov	e|P	e|R	e|F	e|F_SE	o|P	o|R	o|F	o|F_SE
TOTAL	1723	283	505	86	83	0.8589	0.7733	0.8139	0.0012	0.9057	0.8176	0.8594	0.0010
e_1	1088	215	305	54	52	0.8350	0.7810	0.8071	0.0015	0.8812	0.8252	0.8522	0.0013
e_2	375	62	183	29	28	0.8581	0.6720	0.7538	0.0026	0.9290	0.7359	0.8213	0.0022
e_3	260	6	17	3	3	0.9774	0.9386	0.9576	0.0011	0.9888	0.9500	0.9690	0.0009


### 2) MentionLevelEvaluator *[exact_or_overlapping and exact_or_overlapping]*

class	tp	fp	fn	fp_ov	fn_ov	e|P	e|R	e|F	e|F_SE	o|P	o|R	o|F	o|F_SE
TOTAL	1809	197	422	0	0	0.9018	0.8108	0.8539	0.0011	0.9018	0.8108	0.8539	0.0011
e_1	1142	161	253	0	0	0.8764	0.8186	0.8466	0.0012	0.8764	0.8186	0.8466	0.0013
e_2	404	33	155	0	0	0.9245	0.7227	0.8112	0.0023	0.9245	0.7227	0.8112	0.0023
e_3	263	3	14	0	0	0.9887	0.9495	0.9687	0.0009	0.9887	0.9495	0.9687	0.0009


### 3) EntityEvaluator *[overlapping and without comparing entities with normalisation Id's]*

class	tp	fp	fn	fp_ov	fn_ov	e|P	e|R	e|F	e|F_SE	o|P	o|R	o|F	o|F_SE
TOTAL	1810	197	422	0	0	0.9018	0.8109	0.8540	0.0010	0.9018	0.8109	0.8540	0.0010
e_1	1143	161	253	0	0	0.8765	0.8188	0.8467	0.0013	0.8765	0.8188	0.8467	0.0013
e_2	404	33	155	0	0	0.9245	0.7227	0.8112	0.0022	0.9245	0.7227	0.8112	0.0023
e_3	263	3	14	0	0	0.9887	0.9495	0.9687	0.0008	0.9887	0.9495	0.9687	0.0009


*The EntityEvaluator and MentionLevelEvaluator have same entities with one entity less in MentionLevelEvaluator*

**Comment by MadhukarSP** [comment]
### EntityEvaluator [With normalisation Id's and evaluation_level=2]
1) ENTITY_MAP_FUN = 'lowercased'
2) ENTITY_ACCEPT_FUN = str.__eq__

class	tp	fp	fn	fp_ov	fn_ov	e|P	e|R	e|F	e|F_SE	o|P	o|R	o|F	o|F_SE
TOTAL	1723	283	505	0	0	0.8589	0.7733	0.8139	0.0012	0.8589	0.7733	0.8139	0.0012
e_1	1088	215	305	0	0	0.8350	0.7810	0.8071	0.0015	0.8350	0.7810	0.8071	0.0015
e_2	375	62	183	0	0	0.8581	0.6720	0.7538	0.0025	0.8581	0.6720	0.7538	0.0027
e_3	260	6	17	0	0	0.9774	0.9386	0.9576	0.0010	0.9774	0.9386	0.9576	0.0010

**Comment by juanmirocks** [comment]
Done
